	var html = '<div class="box">It works from content.js.</div>'
		+'<div class="square">这里测试一下方块</div>'
		+'<div class="button">这里是按钮</div>'
		+'<div class="container">'
		+'<div class="item">'
		+'<a href="#">1</a>'
		+'<a href="#">2</a>'
		+'<a href="#">3</a>'
		+'<a href="#">4</a>'
		+'<a href="#">5</a>'
		+'<a href="#">6</a>'
		+'<a href="#">7</a>'
		+'</div>'
		+'<div class="item">'
		+'<a href="#">1</a>'
		+'<a href="#">2</a>'
		+'<a href="#">3</a>'
		+'<a href="#">4</a>'
		+'<a href="#">5</a>'
		+'<a href="#">6</a>'
		+'<a href="#">7</a>'
		+'</div>'
		+'<div class="item">'
		+'<a href="#">1</a>'
		+'<a href="#">2</a>'
		+'<a href="#">3</a>'
		+'<a href="#">4</a>'
		+'<a href="#">5</a>'
		+'<a href="#">6</a>'
		+'<a href="#">7</a>'
		+'</div>'
		+'<div class="item">'
		+'<a href="#">1</a>'
		+'<a href="#">2</a>'
		+'<a href="#">3</a>'
		+'<a href="#">4</a>'
		+'<a href="#">5</a>'
		+'<a href="#">6</a>'
		+'<a href="#">7</a>'
		+'</div>'
		+'</div>'
		+'<p>这里是段落内容abcd</p>';
module.exports = html;